import { Employee, Department, Project, Permission, Announcement } from '@/types'

const now = new Date().toISOString()

// ─── Departments ────────────────────────────────────────────────

export const DEFAULT_DEPARTMENTS: Department[] = [
  {
    id: 'dept-it',
    name: '資訊部',
    description: '負責公司資訊系統開發與維護',
    permissions: [
      'it.read', 'it.write',
      'reports.read', 'reports.write',
      'projects.read', 'projects.write',
      'audit.read',
      'settings.read', 'settings.write',
      'admin.read',
    ] as Permission[],
    memberIds: ['emp-it-mgr', 'emp-it-1', 'emp-it-2', 'emp-it-3', 'emp-it-4'],
    managerId: 'emp-it-mgr',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dept-sales',
    name: '業務部',
    description: '負責產品銷售與客戶關係管理',
    permissions: [
      'sales.read', 'sales.write',
      'reports.read', 'reports.write',
      'projects.read',
    ] as Permission[],
    memberIds: ['emp-sales-mgr', 'emp-sales-1', 'emp-sales-2', 'emp-sales-3'],
    managerId: 'emp-sales-mgr',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dept-hr',
    name: '人資部',
    description: '負責人力資源管理與員工事務',
    permissions: [
      'hr.read', 'hr.write',
      'reports.read', 'reports.write',
      'projects.read',
    ] as Permission[],
    memberIds: ['emp-hr-mgr', 'emp-hr-1', 'emp-hr-2', 'emp-hr-3'],
    managerId: 'emp-hr-mgr',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dept-mgmt',
    name: '管理層',
    description: '公司最高管理層，擁有所有系統權限',
    permissions: [
      'admin.read', 'admin.write',
      'hr.read', 'hr.write',
      'sales.read', 'sales.write',
      'it.read', 'it.write',
      'finance.read', 'finance.write',
      'reports.read', 'reports.write',
      'projects.read', 'projects.write',
      'audit.read',
      'settings.read', 'settings.write',
    ] as Permission[],
    memberIds: ['emp-boss'],
    managerId: 'emp-boss',
    createdAt: now,
    updatedAt: now,
  },
]

// ─── Employees ──────────────────────────────────────────────────

export const DEFAULT_EMPLOYEES: Employee[] = [
  // 老闆
  {
    id: 'emp-boss',
    name: '林總經理',
    email: 'boss@erp.com',
    phone: '0900-000-001',
    position: '總經理',
    employeeNumber: 'EMP000',
    status: 'active',
    loginEnabled: true,
    password: 'boss1234',
    forcePasswordChange: false,
    departmentIds: ['dept-mgmt'],
    isManager: true,
    createdAt: now,
    updatedAt: now,
  },
  // 資訊部
  {
    id: 'emp-it-mgr',
    name: '張信良',
    email: 'it.mgr@erp.com',
    phone: '0900-001-001',
    position: '資訊部經理',
    employeeNumber: 'EMP101',
    status: 'active',
    loginEnabled: true,
    password: 'it.mgr123',
    forcePasswordChange: false,
    departmentIds: ['dept-it'],
    isManager: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-it-1',
    name: '林志豪',
    email: 'it1@erp.com',
    phone: '0900-001-002',
    position: '資深工程師',
    employeeNumber: 'EMP102',
    status: 'active',
    loginEnabled: true,
    password: 'it1pass',
    forcePasswordChange: false,
    departmentIds: ['dept-it'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-it-2',
    name: '陳怡君',
    email: 'it2@erp.com',
    phone: '0900-001-003',
    position: '前端工程師',
    employeeNumber: 'EMP103',
    status: 'active',
    loginEnabled: true,
    password: 'it2pass',
    forcePasswordChange: false,
    departmentIds: ['dept-it'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-it-3',
    name: '黃建宏',
    email: 'it3@erp.com',
    phone: '0900-001-004',
    position: '後端工程師',
    employeeNumber: 'EMP104',
    status: 'active',
    loginEnabled: true,
    password: 'it3pass',
    forcePasswordChange: false,
    departmentIds: ['dept-it'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-it-4',
    name: '吳宗霖',
    email: 'it4@erp.com',
    phone: '0900-001-005',
    position: 'DevOps 工程師',
    employeeNumber: 'EMP105',
    status: 'active',
    loginEnabled: true,
    password: 'it4pass',
    forcePasswordChange: false,
    departmentIds: ['dept-it'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  // 業務部
  {
    id: 'emp-sales-mgr',
    name: '王美琪',
    email: 'sales.mgr@erp.com',
    phone: '0900-002-001',
    position: '業務部經理',
    employeeNumber: 'EMP201',
    status: 'active',
    loginEnabled: true,
    password: 'sales.mgr123',
    forcePasswordChange: false,
    departmentIds: ['dept-sales'],
    isManager: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-sales-1',
    name: '李俊傑',
    email: 'sales1@erp.com',
    phone: '0900-002-002',
    position: '業務專員',
    employeeNumber: 'EMP202',
    status: 'active',
    loginEnabled: true,
    password: 'sales1pass',
    forcePasswordChange: false,
    departmentIds: ['dept-sales'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-sales-2',
    name: '許雅雯',
    email: 'sales2@erp.com',
    phone: '0900-002-003',
    position: '業務專員',
    employeeNumber: 'EMP203',
    status: 'active',
    loginEnabled: true,
    password: 'sales2pass',
    forcePasswordChange: false,
    departmentIds: ['dept-sales'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-sales-3',
    name: '劉承恩',
    email: 'sales3@erp.com',
    phone: '0900-002-004',
    position: '業務助理',
    employeeNumber: 'EMP204',
    status: 'active',
    loginEnabled: true,
    password: 'sales3pass',
    forcePasswordChange: false,
    departmentIds: ['dept-sales'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  // 人資部
  {
    id: 'emp-hr-mgr',
    name: '陳淑芬',
    email: 'hr.mgr@erp.com',
    phone: '0900-003-001',
    position: '人資部經理',
    employeeNumber: 'EMP301',
    status: 'active',
    loginEnabled: true,
    password: 'hr.mgr123',
    forcePasswordChange: false,
    departmentIds: ['dept-hr'],
    isManager: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-hr-1',
    name: '蔡宗翰',
    email: 'hr1@erp.com',
    phone: '0900-003-002',
    position: '人資專員',
    employeeNumber: 'EMP302',
    status: 'active',
    loginEnabled: true,
    password: 'hr1pass',
    forcePasswordChange: false,
    departmentIds: ['dept-hr'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-hr-2',
    name: '鄭欣怡',
    email: 'hr2@erp.com',
    phone: '0900-003-003',
    position: '人資專員',
    employeeNumber: 'EMP303',
    status: 'active',
    loginEnabled: true,
    password: 'hr2pass',
    forcePasswordChange: false,
    departmentIds: ['dept-hr'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'emp-hr-3',
    name: '洪志明',
    email: 'hr3@erp.com',
    phone: '0900-003-004',
    position: '招募專員',
    employeeNumber: 'EMP304',
    status: 'active',
    loginEnabled: true,
    password: 'hr3pass',
    forcePasswordChange: false,
    departmentIds: ['dept-hr'],
    isManager: false,
    createdAt: now,
    updatedAt: now,
  },
]

// ─── Projects ───────────────────────────────────────────────────

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: 'proj-erp',
    name: 'ERP 系統開發',
    description: '公司內部 ERP 系統建置與維護',
    departmentId: 'dept-it',
    managerId: 'emp-it-mgr',
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'proj-app',
    name: '行動應用程式',
    description: '客戶端行動 App 開發',
    departmentId: 'dept-it',
    managerId: 'emp-it-mgr',
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'proj-sales-q2',
    name: 'Q2 業務推廣',
    description: '第二季業務拓展計畫',
    departmentId: 'dept-sales',
    managerId: 'emp-sales-mgr',
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'proj-recruit',
    name: '人才招募計畫',
    description: '年度人才招募與培訓',
    departmentId: 'dept-hr',
    managerId: 'emp-hr-mgr',
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
]

// ─── Announcements ───────────────────────────────────────────────

export const DEFAULT_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '歡迎使用 ERP 系統',
    content: '本系統提供員工管理、專案追蹤、工作日報等功能，如有任何問題請聯絡資訊部。',
    authorId: 'emp-boss',
    authorName: '林總經理',
    pinned: true,
    createdAt: now,
  },
  {
    id: 'ann-2',
    title: '三月份全體員工會議通知',
    content: '請全體員工於本月最後一個工作天下午 3 點至會議室參加月度例會，請準時出席。',
    authorId: 'emp-hr-mgr',
    authorName: '陳淑芬',
    pinned: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
]
